<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Андрій Негрич Дмитрович</title>
  <style>
    body {
      font-family: 'Segoe UI', sans-serif;
      background-color: #121212;
      color: #e0e0e0;
      margin: 0;
      padding: 0;
    }
    header {
      background-color: #1f1f1f;
      text-align: center;
      padding: 40px 20px;
      border-bottom: 2px solid #333;
    }
    header h1 {
      font-size: 36px;
      margin: 0;
      color: #ffffff;
    }
    header p {
      color: #aaaaaa;
      font-size: 18px;
    }
    main {
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      background-color: #1a1a1a;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(255, 255, 255, 0.05);
    }
    p {
      font-size: 18px;
      line-height: 1.7;
    }
    footer {
      text-align: center;
      color: #888;
      padding: 30px 20px;
      font-size: 14px;
      border-top: 1px solid #333;
    }
  </style>
</head>
<body>

  <header>
    <h1>Андрій Негрич Дмитрович</h1>
    <p>Громадський діяч, гуманітарний лідер, батько і поет</p>
  </header>

  <main>
    <p><strong>Андрій Негрич Дмитрович</strong> — громадський діяч, керівник представництва благодійного фонду <strong>Global Empowerment Mission (GEM)</strong> в Україні, військовослужбовець у минулому, спортсмен і поет.</p>

    <p>Народився 12 квітня 1983 року в Івано-Франківську. Пройшов службу у Повітряних силах Збройних Сил України. Брав участь у міжнародних змаганнях з жиму штанги лежачи, здобуваючи призові місця.</p>

    <p>Після початку повномасштабної війни очолив українське представництво GEM. Під його керівництвом реалізовано десятки проектів допомоги людям у скруті, зокрема “Віконну програму”, яка допомагає відновлювати пошкоджені будинки у прифронтових зонах.</p>

    <p>Окрім благодійної діяльності, Андрій — людина творчої душі. Він пише поезію, бере участь у культурних проєктах та дарує натхнення оточуючим.</p>

    <p>Для рідних він — надійний, мудрий, добрий батько й приклад справжньої сили духу. Його життєва позиція — допомагати, не здаватися і нести світло навіть у найтемніші часи.</p>
  </main>

  <footer>
    З любов’ю, від Давида| © 2025
  </footer>

</body>
</html>
